### ISSUE TITLE
デフォルトのviewがかっこわるい

### ISSUE THREAD

**Issue by masarakki** [rosylilly/mount_doc#3]
bootstrapでいいじゃん

**Comment by rosylilly** [comment]
Bootstrap 嫌いなんですけど、最近のはちょっとはマシみたいなので気が向いたら手直しする。

**Comment by rosylilly** [comment]
@masarakki fixed design. please review a new design :wink:

**Comment by masarakki** [comment]
+1

**Comment by rosylilly** [comment]
thx :+1:
